returntocorp/semgrep-rules

- python/django/performance-improvements.yaml
- python/sqlalchemy/delete-where.yaml
- python/sqlalchemy/performance-improvements.yaml
- `delete-where-no-execute`: Running `delete().where(...)` without execution in Sqlachemy results in a no-op. An alternative is to run `filter(...).delete()` instead.
- `access-foreign-keys`: Instead of using `.user.id`, which calls an extra query, you can run `.user_id` for most databases 
- `len-all-count`: Running `.count()` rather than `len(...all())` sends less data to the client since the method is performed server side, so this results in a performance improvement.
- `batch-import`: Rather than adding elements one at a time from Sqlalchemy, batch imports can be performed such as 
```
batch = []
insert_stmt = Object.__table__.insert()
for $X in $Y:
if len(batch) > 1000:
db.session.execute(insert_stmt, batch)
batch.clear()
batch.append($X)
if batch:
db.session.execute(insert_stmt, …
```
> Added new SQLAlchemy and Django checks

- java/basic-rules.yaml
- python/sqlalchemy/delete-where.yaml
- tests/java/assignment-comparison.java
- tests/python/django/sensitive-variables.py
- tests/python/sqlalchemy/delete-where.py
- tests/python/sqlalchemy/performance-test.py
The conditions were incorrect for the initial Sqlachemy check, so I fixed the pattern matching. I also added tests to start the process of verifying the Django, Sqlachemy, and Java checks. 
- In pfff: 
`./configure && make depend && make && make opt`
- In sgrep: 
```
dune build
cp ./_build/default/bin/main_sgrep.exe /usr/local/bin/sgrep
cp ./sgrep.py /usr/local/bin/sgrep-lint
sgrep-lint <YAML_FILE_OR_DIRECTORY> <code to check>
```
Alternatively
```
./_build/default/bin/main_sgrep.exe -lang <java/python/javascript/etc> -e '<pattern>' /path/to/java/dir/
```
> Fixed Sqlachemy check and added new tests

- python/flask/secure-static-file-serve.yaml
- tests/python/flask/send_static_file/test_send_file_without_path_sanitization.py
Adds a check when there might be a dataflow from user input to a sink.
"How to serve static files in Flask" is the most asked question in Stackoverflow for Flask. Hence, this will be a popular check if we do it right.
Pending `def $X(filename: $Y, ...):` support integration in https://github.com/returntocorp/sgrep. 
Testing: 
1) Run rule 
```
sgrep-lint ~/Workspace/sgrep-rules/python/flask/secure-static-file-serve.yaml ~/Workspace/sgrep-rules/tests/python/flask/send_static_file/test_send_file_without_path_sanitization.py| jq
```
2) See it fire on 
```
@app.route("/<path:filename>")
def download_file(filename):
return send_file(filename) .  ## CATCHES THIS
```
> Add send_file warning

- python/deadcode/missing-fstring.yaml
- tests/python/deadcode/missing-fstring.py
not currently working; cc @aryx ; I'm not sure on the right syntax to use inside the print(...) specifier:
`print('...{$X}...')`
> find variables used in strings that should probably be fstrings

- test.py
(also, ran black on project)
new output when tests fail:
```
================================================================================
final confusion matrix: TP: 29	TN:0	 FP: 0	 FN: 6
2 checks failed tests (run with verbose flag for more details)
failing checks:
✖ FAILED file: python/smells/return-in-init.yaml check: yield-in-init
✖ FAILED file: python/smells/return-in-init.yaml check: return-in-init
```
> improve test suite output

- test.py
New output that shows expected vs reported lines:
```
failing checks:
✖ FAILED rule file: python/deadcode/useless-eqeq.yaml check: eqeq-is-bad
in test: sgrep-rules/python/deadcode/useless-eqeq.py, expected lines: {3, 22} != reported: {3, 15, 22, 7}
```
> better test output for debugging

- python/flask/use-jsonify/use-jsonify.py
- python/flask/use-jsonify/use-jsonify.yaml
We have https://checks.bento.dev/en/latest/flake8-flask/use-jsonify/
this re-does it in sgrep in 1/10 the time it took.
Addresses https://github.com/returntocorp/sgrep-rules/issues/123
> Reimplements jsonify check in sgrep

- python/smells/list-modify-iterating.py
- python/smells/list-modify-iterating.yaml
The existing implementation of this check had to use a large number of
patterns, as matching class inclusion in a pattern means only
a statement can be matched.
Instead, use the pattern-inside helper to determine class inclusion, in
which case a pattern can match any expression.
As a bonus, the check now reports the smell line, as opposed to the line
at which the enclosing class is defined.
> Clean up smells/list-modify-iterating check

- python/django/django-2_0-compat.py
- python/django/django-2_0-compat.yaml
This commit implements five Django 2.0 compatibility rules for sgrep.
I'm pushing these as an initial set to see what our fire frequency is on
Django projects. If the enterprise seems worthwhile, I'll continue
implementing compatibility checks.
These checks are sourced from
https://docs.djangoproject.com/en/3.0/internals/deprecation/.
> Initial set of django 2.0 compatibility rules

- test.py
It's not implemented in sgrep.py any more
> remove strict parsing flag

- python/smells/manual-collections-create.py
- python/smells/manual-collections-create.yaml
Detects manual implementation of [`collections.Counter`](https://docs.python.org/3.8/library/collections.html#collections.Counter) and [`collections.defaultdict`](https://docs.python.org/3.8/library/collections.html#collections.defaultdict).
Tested with:
```
$ docker run --rm -v $(pwd):/home/repo returntocorp/sgrep:develop -f /home/repo/python/smells/manual-collections-create.yaml /home/repo/python/smells/manual-collections-create.py | grep "manually creating a"
running 4 rules from 1 yaml files (0 yaml files were invalid)
rule:python.smells.manual-counter-create: manually creating a counter - use collections.Counter
rule:python.smells.manual-defaultdict-dict-create: manually creating a defaultdict - use collections.defaultdict(dict)
rule:python.smells.manual-defaultdict-dict-create: …
```
> Add rule for detecting manual reimplementation of 'collections' funtionality

- python/django/security/secure-cookies.py
- python/django/security/secure-cookies.yml
This was a relatively successful check in our flask corpus. I've ported
it to Django here.
Interestingly, there's not a good way to identify that the set_cookie
method is being called on an HttpResponse object without some
rudimentary typing or dataflow. So I just use the common identifier
"response" as the invocation target. Note that this means that this
check fires on Flask projects.
In order to have this not fire on random Django middleware vendored
code, I excluded expressions from common Django middlewares.
After doing this, the fire frequency on non-test, non-vendored code is
1 finding in the entire Django-500 corpus. It's a true positive.
For details, see:
https://dev.massive.ret2.co/jobs/618?page=1&sort_on=repo_url&sort_by=asc
> Copy secure-set-cookie to django

- template.yaml
`template.yaml` is likely the first place new users will look when writing their own rules. These rules are probably firing on their code, or someone they knows code - let's avoid calling them out.
> Avoid calling people out over their bugs

- python/flask/deprecated-apis.py
- python/flask/deprecated-apis.yaml
This information was mostly gleaned by searching [Flask's CHANGELOG](https://github.com/pallets/flask/blob/master/CHANGES.rst) for "deprecated." There were a few more, but it's probably not necessary to search for things deprecated/removed in 2011. Once https://github.com/returntocorp/sgrep/issues/197 is in we'll be able to search for `flask.ext` use as well.
Fixes https://github.com/returntocorp/sgrep-rules/issues/159
> Fix #159, add rule for deprecated Flask APIs

- java/basic-rules.yaml
- java/hardcoded-conditional.py
- java/hardcoded-conditional.yaml
Move hardcoded-conditional tests and rules to their own file so they
do not interfear with the other tests and cause tests to fail.
> Fix: Split out java tests

- javascript/jwt-hardcode/example1.js
- javascript/jwt-hardcode/example2.js
- javascript/jwt-hardcode/example3.js
- javascript/jwt-hardcode/example4.js
- javascript/jwt-hardcode/example5.js
- javascript/jwt-hardcode/jwt-hardcode.yaml
- javascript/jwt-hardcode/simple-examples.js
**Description:**
the rule is intended to find hardcoded secret values while generating or verifying JWTs
it covers 2 most popular modules: [`jsonwebtoken`](https://www.npmjs.com/package/jsonwebtoken) and [`jose`](https://www.npmjs.com/package/jose)
examples:
```javascript
const jsonwt = require('jsonwebtoken')
const secret = 'hardcoded-secret'
const token1 = jsonwt.sign({foo: 'bar'}, secret)
const token2 = jsonwt.verify({foo: 'bar'}, 'hardcoded-secret')
```
```javascript
const jose = require('jose')
const { JWK, JWT } = jose
const token3 = JWT.sign(payload, 'hardcoded-secret')
const token4 = JWT.verify(payload, JWK.asKey('hardcoded-secret'))
```
**AST rules:**
to back my research on this one I created a `stadt` rule
https://github.com/inkz/typed-ast-rules-example/blob/2acada8e3f1958becfe16 …
> add jwt-hardcode rule for javascript

- python/flask/different-route-names.py
- python/flask/different-route-names.yaml
1. Using single instead of double quotes in string literals (IMO sgrep
should deal with this for you)
2. Defining converters in the route (see
https://flask.palletsprojects.com/en/1.1.x/quickstart/#variable-rules)
> Fix two false positives in flask-view-func-match-route-params

- python/smells/open-never-closed.py
- python/smells/open-never-closed.yml
In many cases, this pattern is a true positive:
fd = open(...)
do_something()
fd.close()
As do_something() can raise an exception.
However, this pattern is correct:
fd = open(...)
try:
do_something()
finally:
fd.close()
In this commit I merely remove the false positive, rather than
broadening the scope of the check to include these true positives.
> Fix FP in python/smells/open-never-closed

- python/smells/list-modify-iterating.py
- python/smells/list-modify-iterating.yaml
Leverages deep-expression matching to remove a false positive where this
would fire on _any_ list modification in a for loop, even if it was not
the list under iteration.
A downside of this change is that the rule now fires on the enclosing
iteration, instead of the offending list modification.
> Remove FP in python/smells/list-modify-iterating

- python/django/security/secure-cookies.yml
Previously, this check fired on Flask as well.
To validate, just run on
python/flask/secure-cookies/response-set-cookie.py.
> Django: scope secure cookie check to Django

- python/django/security/csrf-exempt.py
- python/django/security/csrf-exempt.yaml
Updated test for no-csrf-exempt now that https://github.com/returntocorp/sgrep/issues/294 is working. Renamed check_id to 'no-csrf-exempt' and renamed files to 'csrf-exempt'.
> Updated test for csrf-exempt

- Pipfile
- python/django/security/README.md
- python/django/security/generate-injection.py
- python/django/security/ssrf-injection-requests.py
- python/django/security/ssrf-injection-requests.yaml
- python/django/security/ssrf-injection-urllib.py
- python/django/security/ssrf-injection-urllib.yaml
- python/django/security/templates/injection-template.yaml.j2
Detects SSRF injection attacks into the requests API.
Neither of these checks actually fire on anything in platform, so
they're pretty speculative.
For completeness, I had to write 48 different patterns for each sink. :(
This cardinality is the product space of
- Django import identification (import HttpResponse and import render)
- Request-object data extraction (request[], request.get,
request.body[], request.body.get)
- Possible ways of embedding the injection expression (bare, assignment, return) -- note that this is incomplete, as there is also call site
- Injection methods (method call, e.g. by string format, and f-strint)
In order to streamline this generation in the future, I add jinja
templating.
For instance, to generate ssrf-injection-requests.yaml, I ran:
```bash …
```
> Add python/django/security/ssrf-injection-requests

- go/gosec/pprof/pprof.yaml
- go/gosec/pprof/pprof_1.go
- go/gosec/pprof/pprof_2.go
- go/gosec/pprof/pprof_3.go
This is a one of 4 high severity checks in gosec.
The check detects import "_ net/http/pprof" with non-local http server. Blank imports assumes the side-effect of the package which in this case opens a /debug route.
This furthers [the check G108](https://github.com/securego/gosec/blob/master/rules/pprof.go
)  by adding a filter for localhost.
More on the problem in https://www.farsightsecurity.com/blog/txt-record/go-remote-profiling-20161028/
> Add pprof check (G108) to sgrep

- go/gosec/overflow/overflow.yaml
- go/gosec/overflow/overflow_int16.go
- go/gosec/overflow/overflow_int32.go
Adds integer overflow detection for int16/int32 calls with
data flowing from strconv.Atoi.
It furthers [G109](https://github.com/securego/gosec/blob/master/rules/integer_overflow.go
) by actually validating the data flow and validating the string literal against against https://golang.org/pkg/builtin/#int32
> Add integer overflow (G109) check for overflow

- javascript/jwt-hardcode/jwt-hardcode.js
Really deep stmt matching probably allows to report this new error
test plan:
~/github/sgrep/sgrep_lint/sgrep.py --dangerously-allow-arbitrary-code-execution-from-rules --strict --test --test-ignore-todo .
> * javascript/jwt-hardcode/jwt-hardcode.js: Fix todoruleid

- go/gosec/tls_ssl_blacklist/tls.go
- go/gosec/tls_ssl_blacklist/tls.yaml
The blacklist is based on the recommendation of the pkg maintainer:
https://golang.org/src/crypto/tls/cipher_suites.go?s=3635:3677#L71
> TLS blacklist rule

- go/gosec/bad_imports/insecure_ssh.go
- go/gosec/bad_imports/insecure_ssh.yaml
Based on https://skarlso.github.io/2019/02/17/go-ssh-with-host-key-verification/,
its worth highlighting this check.
> Port over G106

- python/django/security/injection/reflected-data-httpresponse.yaml
- python/flask/security/open-redirect.yaml
- python/flask/security/render-template-string.yaml
- python/flask/security/unsanitized_input.yaml
Cleanup all cases of matching `return`, `$A =` as detected by `semgrep --lint`
> semgrep --lint is clean now

- python/lang/security/deserialization/pickle.py
- python/lang/security/deserialization/pickle.yaml
This adds blacklist of pickle, cPickle, dill, and shelve.
Addresses a part of https://github.com/returntocorp/semgrep-rules/issues/511
> Add Pickle related deserialization checks
