returntocorp/semgrep-rules

python/smells/missing-hash-with-eq.py
python/smells/return-in-init.py

Will pass once https://github.com/returntocorp/sgrep/pull/85 is merged

mark rule as working

---

python/deadcode/return.yaml
python/deadcode/useless-eqeq.py
python/exceptions/exceptions.py
python/exceptions/exceptions.yaml

enable more tests

---

python/smells/unchecked-returns.py
python/smells/unchecked-returns.yaml

I noticed this from a bug report to airflow

unchecked subprocess call

---

python/django/db/model-save.py
python/django/db/model-save.yaml

django: add model save missing super call rule

---

python/flask/same-handler-name.py
python/flask/same-handler-name.yaml

Add flask duplicate handler name check

---

python/django/json_response/json_response.py
python/django/json_response/json_response.yaml
python/smells/dict-modify-iterating.yaml

Addresses  https://github.com/returntocorp/sgrep-rules/issues/91
Testing with `./test.py -v -sv -s python/django`

Add JsonResponse Upsell check

---

python/django/security/csrf_exempt.py
python/django/security/csrf_exempt.yaml

add simple csrf_exempt example

---

python/django/db/upsell_count.py
python/django/db/upsell_count.yaml

Addresses https://github.com/returntocorp/sgrep-rules/issues/97
Test with:
```
docker run --rm -v $(pwd):/home/repo returntocorp/sgrep:develop --config python/django/db/upsell_count.yaml python/django/db/upsell_count.py
```

Upsell count() method

---

python/django/db/query/query_set_extra.py
python/django/db/query/query_set_extra.yaml

Addresses https://github.com/returntocorp/sgrep-rules/issues/80
To test:
```
docker run --rm -v $(pwd):/home/repo returntocorp/sgrep:develop --config python/django/db/query/query_set_extra.yaml python/django/db/query/query_set_extra.py
```

Non type-aware django .extra() detection

---

python/django/security/raw_query.py
python/django/security/raw_query.yaml

Addresses https://github.com/returntocorp/sgrep-rules/issues/81
Test with
```
docker run --rm -v $(pwd):/home/repo returntocorp/sgrep:develop --config python/django/security/raw_query.yaml python/django/security/raw_query.py
```

Avoid raw()/RawSQL() API-s

---

test.py

enable flags merged in https://github.com/returntocorp/sgrep/pulls/194

use strict parsing flag

---

python/django/performance/upsell_earliest_latest.py
python/django/performance/upsell_earliest_latest.yaml

Addresses https://github.com/returntocorp/sgrep-rules/issues/92
Test with:
```
docker run --rm -v $(pwd):/home/repo returntocorp/sgrep:develop --config python/django/performance/upsell_earliest_latest.yaml python/django/performance 
```

Upsell latest/earliest

---

python/flask/open-redirect/open-redirect.py
python/flask/open-redirect/open-redirect.yml

This check looks for data going from `requests.*` into `flask.redirect` implying user control of where to redirect.
https://dev.massive.ret2.co/jobs/587?page=1&sort_on=repo_url&sort_by=asc

Open Redirects in Flask

---

python/certificates/disabled-cert-validation.py
python/certificates/disabled-cert-validation.yaml

Requires https://github.com/returntocorp/sgrep/pull/198

check for connections over HTTP or disabling certs with HTTPS (superset of DUO132)

---

python/django/best_practices/django_os.py
python/django/best_practices/environ.py
python/django/best_practices/os_django.py
python/django/best_practices/upsell_django_environ.yaml

Addresses https://github.com/returntocorp/sgrep-rules/issues/113
There is a known false positive already.

Upsell django-environ

---

python/flask/render-template-string/render-template-string.py
python/flask/render-template-string/render-template-string.yml

Added check for rendering template strings that have been string formatted or appended to.

New Check for Flask: Rendering string-formatted templates

---

python/deadcode/baseclass-attribute-override.py

see https://github.com/returntocorp/sgrep/issues/260

mark rule as regression

---

python/flask/different-route-names.py
python/flask/different-route-names.yaml

detect different route names in flask

---

.github/ISSUE_TEMPLATE/check.md

This includes instructions for information to include in the ticket before closing the ticket.

Added an issue template for new checks.

---

javascript/deadcode/useless-assign.js
javascript/deadcode/useless-assign.yaml

This particular false positive seems to crop up very frequently in OSS projects.

fix fp in js useless assignment

---

java/basic-rules.java
java/basic-rules.yaml

x != x is often used to test if x is a numeric value. Since Java
1.early, one can just use Double.isNaN, so recommend this.

Improve java.eqeq-is-bad message

---

go/net/formatted-template-string.go
go/net/formatted-template-string.yaml

Added a new check for formatted/concatenated strings into template.HTML which does not escape input.

Added a new check for formatted/concatenated strings into template.HTML

---

go/jwt/jwt.go
go/jwt/jwt.yaml

Addresses fixes from https://github.com/returntocorp/sgrep/pull/339

update test suite

---

python/django/security/sql_injection_extra.py
python/django/security/sql_injection_extra.yaml

Adds SQLi checks for extra() using const propagation.
Addresses last piece of https://github.com/returntocorp/sgrep-rules/issues/263

SQLi check for extra()

---

python/flask/unsanitized_input.py
python/flask/unsanitized_input.yaml

Looks for calls to make_response using unsanitized request parameters.
Closes #210 .

Check for unsanitized reflection into flask.make_response

---

python/django/security/sql-injection-using-db-cursor-execute.py
python/django/security/sql-injection-using-db-cursor-execute.yaml

Addresses https://github.com/returntocorp/sgrep-rules/issues/283

Add SQLi detection for execute() sink

---

python/django/security/user-open.py
python/django/security/user-open.yaml

Addresses https://github.com/returntocorp/sgrep-rules/issues/268

Added check for user data going into open()

---

python/django/security/csrf-exempt.py
python/django/security/csrf-exempt.yaml
python/django/security/user-eval-format-string.py
python/django/security/user-eval-format-string.yaml
python/django/security/user-eval.py
python/django/security/user-eval.yaml
python/django/security/user-exec-format-string.py
python/django/security/user-exec-format-string.yaml
python/django/security/user-exec.py
python/django/security/user-exec.yaml

Addresses https://github.com/returntocorp/sgrep-rules/issues/260

Added checks for user data going into eval and exec.

---

python/django/security/path-traversal-file-name.py
python/django/security/path-traversal-file-name.yaml

Add checks for detecting when request data flows into formatted file names.
Addresses https://github.com/returntocorp/sgrep-rules/issues/282

Injection to file name

---

python/django/security/request-data-write.py
python/django/security/request-data-write.yaml

This wasn't a ticket. Just an experiment. After review of findings I don't think it's actually a good "injection" check.
Findings: https://dev.massive.ret2.co/triager/filter/812

New check for request data going into .write

---

python/django/security/mass-assignment.py
python/django/security/mass-assignment.yaml

Addresses: https://github.com/returntocorp/sgrep-rules/issues/289

New check for mass assignment.

---

python/django/security/generate-injection.py
python/django/security/xss-send-mail-html-message.py
python/django/security/xss-send-mail-html-message.yaml

Addresses second half of https://github.com/returntocorp/sgrep-rules/issues/266

New check for send_mail, which is slightly different than EmailMessage.

---

java/hardcoded-conditional.java
java/hardcoded-conditional.yaml
python/deadcode/useless-comparison.yaml

Test plan:
~/github/sgrep/sgrep_lint/sgrep.py --test --strict --test-ignore-todo --dangerously-allow-arbitrary-code-execution-from-rules .
All tests passed.

Use new operator <... ...> for deep expression matching and fix current regression

---

go/gorilla/handler-assignment-from-multiple-sources.go
javascript/deadcode/useless-assign.js

Thx to https://github.com/returntocorp/sgrep/pull/432 a few new errors
can be detected!
Test plan:
with a build of sgrep after pull/432:
~/github/sgrep/sgrep_lint/sgrep.py --dangerously-allow-arbitrary-code-execution-from-rules --strict --test --test-ignore-todo .
pass now all tests

Fix regression of https://github.com/returntocorp/sgrep/pull/432

---

javascript/spawn-git-clone/spawn-git-clone.js
javascript/spawn-git-clone/spawn-git-clone.yaml

Rule for https://github.com/returntocorp/semgrep-rules/issues/400

Add spawn-git-clone rule

---

go/gosec/socket/bind_all.go
go/gosec/socket/bind_all.yaml
go/gosec/socket/bind_all_default.go

Detection for bind all for '0.0.0.0'. This is similar to python/socket

Port over G102

---

go/gosec/traversal/zip.go
go/gosec/traversal/zip.yaml

The issue is discussed in https://github.com/securego/gosec/issues/205 and 
it seems to detect a real path traversal.

Port over G305

---

go/gosec/bad_temp_file/bad_tmp.go
go/gosec/bad_temp_file/bad_tmp.yaml

Bad temp file creatiojn is CWE: 377

Port over G303

---

go/gosec/dos/decompression_bomb.yaml
go/gosec/dos/zip_bomb.go
go/gosec/dos/zlib_bomb.go

Potential DOS via decomp. bomb. Used bomb.codes as a reference point.

Port over G110

---

java/lang/security/audit/script-engine-injection.java
java/lang/security/audit/script-engine-injection.yaml

rule for https://github.com/returntocorp/semgrep-rules/issues/435

add script-engine-injection rule

---

java/lang/security/audit/crypto/weak-hash.java
java/lang/security/audit/crypto/weak-hash.yaml

Addresses https://github.com/returntocorp/semgrep-rules/issues/462
Adds checks for SHA1 and MD5 usage in Java.

Add FindSec Java weak hash func checks

---

java/lang/security/audit/ldap-injection.java
java/lang/security/audit/ldap-injection.yaml

rule for https://github.com/returntocorp/semgrep-rules/issues/434

add ldap-injection rule

---

java/security/audit/ldap-entry-poisoning.java
java/security/audit/ldap-entry-poisoning.yaml

Addresses https://github.com/returntocorp/semgrep-rules/issues/459
This add check for https://find-sec-bugs.github.io/bugs.htm#LDAP_ENTRY_POISONING

Java LDAP poisoning check

---

java/lang/security/audit/crypto/ecb-cipher.java
java/lang/security/audit/crypto/ecb-cipher.yaml

Addresses https://github.com/returntocorp/semgrep-rules/issues/454

Cipher in ECB mode check

---

java/lang/security/audit/crypto/weak-rsa.java
java/lang/security/audit/crypto/weak-rsa.yaml

Addresses https://github.com/returntocorp/semgrep-rules/issues/449

RSA weak key check

---

java/lang/security/audit/crypto/rsa-no-padding.java
java/lang/security/audit/crypto/rsa-no-padding.yaml

Addresses https://github.com/returntocorp/semgrep-rules/issues/446

RSA no padding check

---

java/lang/security/audit/crypto/des-is-deprecated.java
java/lang/security/audit/crypto/des-is-deprecated.yaml

addresses https://github.com/returntocorp/semgrep-rules/issues/444

Add check for des-is-deprecated
